config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"

  get '/mylists', to: 'lists#mylists'
  post '/assigntome/:id', to: 'lists#assigntome', as: 'assigntome'

    resources :lists do
      resources :listitems
    end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
    belongs_to :user
    has_many :listitems
end

app/models/listitem.rb
class Listitem < ApplicationRecord
    belongs_to :list
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :lists

  def address
    [city, postcode, country].compact.join(', ')
  end

  geocoded_by :address,
        :latitude => :lat, :longitude => :long
  after_validation :geocode
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception
  before_action :set_locale

 
  ##def switch_locale(&action)
  ##  country = request.location.country_code
  ##  locale = country.downcase
  ##  I18n.with_locale(locale, &action)
  ##end
  
  
  

  ##around_action :switch_locale

   

  

  private
  def set_locale
    I18n.locale = extract_locale || I18n.default_locale
  end
  def extract_locale
    parsed_locale = request.location.country_code.downcase
    I18n.available_locales.map(&:to_s).include?(parsed_locale) ? parsed_locale : nil
  end

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :password, :country, :city, :postcode, :ishelper])
        devise_parameter_sanitizer.permit(:account_update, keys: [:name, :email, :password, :country, :city, :postcode, :ishelper])
      end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController

    def index
        @helpers = User.where(ishelper: true).count
        @allhelpers = User.where.not(lat:nil)
        @circles = [max: 20, min: 5]


        @markers = @allhelpers.map do |helper|
            {
                latlng: [helper[:lat], helper[:long]],
            }
        end


    end
end

app/controllers/listitems_controller.rb
class ListitemsController < ApplicationController

    def create
        @list = List.find(params[:list_id])
        @listitem = @list.listitems.build(listitem_params)
        @listitem.list_id = @list.id
        @listitem.save
        redirect_to @list

    end


    private

        def listitem_params
            params.require(:listitem).permit(:item_text, :item_count, list_attributes: [:id])
        end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
    before_action :authenticate_user!, only: [:new, :create]

    def index
        @lists = List.where(assigned_to: nil)
    end

    def new
        @list = List.new
    end

    def create
        @list = List.new(list_params)
        @list.user_id = current_user.id
        @list.save
        flash[:notice] = "List was saved."
        redirect_to @list
    end

    def show
        @list = List.find(params[:id])
        @listitem = Listitem.new()
    end

    def destroy
        @list = List.find(params[:id])
        @list.listitems.each do |l|
            l.destroy
        end
        @list.destroy
        redirect_to lists_path
    end

    def mylists
        @lists = List.where(user_id: current_user.id)
        @assignedlists = List.where(assigned_to: current_user.id)
    end

    def assigntome
        @list = List.find(params[:id])
        @list.assigned_to = current_user.id
        @list.save
        redirect_to @list
    end

    
    private

    def require_login
        unless user_signed_in?
        flash[:error] = "You must be logged in to access this section"
        redirect_to new_user_session_url # halts request cycle
        end
    end

    def list_params
        params.require(:list).permit(:name, :country, :town, :postcode)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/listitems_helper.rb
module ListitemsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/home/index.html.erb
<h1 class="display-4"><%= t :hello_world %> </h1>
<h4 class="text-muted"><%= t :covid %> </h4>
<div class="row">
  <div class="col-xs-12 col-md-6">
    <p><%= t :platform %></p>
  </div>
    <div class="col-xs-12 col-md-6">
    <p><%= t :riskgroup2 %></p>
  </div>
</div>
<hr>
<div class="row">
  <div class="col-xs-12 col-md-6">
    <h4 class="text-center"><%= t :need_help %></h4>
    <p class="text-center"><%= t :need_help_p %></p>
    <div class="text-center"><%= link_to t(:register_btn), new_user_registration_url, {:class => "btn btn-primary btn-lg mx-auto" }%></div>
  </div>
  <div class="col-xs-12 col-md-6">
    <h4 class="text-center"><%= t :offer_help %></h4>
    <p class="text-center"><%= t :offer_help_p_html %></p>
    <div class="text-center"><%= link_to t(:register_btn), new_user_registration_url, {:class => "btn btn-primary btn-lg mx-auto" }%></div>
  </div>
</div>

<hr>

<div class="row">
<h4><%= t(:map_text, count: @helpers) %></h4>
  <div class="col-xs-12 col-md-12">

<div class="map"></div>

<script>
var map = L.map('map').setView([51.505, -0.09], 13);

L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
    attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
}).addTo(map);

L.marker([51.5, -0.09]).addTo(map)
    .bindPopup('A pretty CSS3 popup.<br> Easily customizable.')
    .openPopup();
</script>

</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shopaid</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta content='maximum-scale=1.0, initial-scale=1.0, width=device-width' name='viewport'>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.6.0/dist/leaflet.css"
  integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ=="
  crossorigin=""/>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.7.1/leaflet.js" integrity="sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <%= favicon_link_tag asset_path("favicon-32x32.png") %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to image_tag("logotext_small.png"), root_path, {:class => "navbar-brand" }%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
      <%= link_to t(:home), root_path, {:class => "nav-link"}%>
      </li>
      <li class="nav-item">
        <%= link_to t(:lists), lists_url, {:class => "nav-link"} %>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to t(:my_lists), mylists_url, class: "nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to t(:my_profile), edit_user_registration_url, class: "nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to "Sign Out", destroy_user_session_url, method: :delete, class: "nav-link logoff"%>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to t(:log_sign), new_user_registration_url, {class: "nav-link"} %>
        </li>
      <% end %>
      
      
    </ul>
  </div>
</nav>
  <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    <%= yield %>
    </div>
    <footer class="footer mt-auto py-3">
      <div class="container">
        <span class="text-muted">&copy; Didrik Birkemalm 2020</span>
      </div>
  </footer>
  </body>
</html>

app/views/lists/_listitemform.html.erb
<%= form_for(:listitem) do |f| %>
    <div class="form-group">
        <%= f.text_field :item_text, :placeholder => "Name item", :class => "form-control" %>
    </div>
    <%= f.submit %>
<% end %>

app/views/lists/index.html.erb
<div class="row">
<div class="col-sm-12">
<h2>Need help to shop?</h2>
<p>Create your list here!</p>
<%= link_to "Create List", new_list_url, :class => "btn btn-success" %>
</div>
</div>
<br>
<div class="row">
<h2 class="col-sm-12">Lists in need of shopping</h2>
<br>
  <% @lists.each do |l|%>
  <div class="col-sm-3">
    <div class="card">
  <div class="card-body">
    <h5 class="card-title"><%= l.name %></h5>
      <span class=""><strong>Country:</strong></span>
      <p class=""><%= l.country %></p>
      <span class=""><strong>Town:</strong></span>
      <p class=""><%= l.town %></p>
      <span class=""><strong>Postcode:</strong></span>
      <p class=""><%= l.postcode %></p>
    <%= link_to "Go To List!", list_url(l.id), :class => "btn btn-primary"%>
  </div>
  </div>
</div>
  <% end%>
</div>

app/views/lists/mylists.html.erb
<h2>My lists</h2>
<div class="row">
  <% @lists.each do |l|%>
  <div class="col-sm-3">
    <% if l.assigned_to == nil %>
        <div class="card">
    <% else %>
        <div class="card assigned">
    <% end %>
  <div class="card-body">
    <h5 class="card-title"><%= l.name %></h5>
    <ul>
      <li><%= l.country %></li>
      <li><%= l.town %></li>
      <li><%= l.postcode %></li>
    </ul>
    <%= link_to "Go To List!", list_url(l.id), :class => "btn btn-primary"%>
  </div>
  </div>
</div>
  <% end%>
</div>
<br>
<hr>
<h2>Lists assigned to me</h2>
<div class="row">

  <% @assignedlists.each do |l|%>
  <div class="col-sm-3">
    <div class="card">
  <div class="card-body">
    <h5 class="card-title"><%= l.name %></h5>
    <ul>
      <li><%= l.country %></li>
      <li><%= l.town %></li>
      <li><%= l.postcode %></li>
    </ul>
    <%= link_to "Go To List!", list_url(l.id), :class => "btn btn-primary"%>
  </div>
  </div>
</div>
  <% end%>
</div>

app/views/lists/new.html.erb
<div class="row">
<h2>Create a shopping list</h2>
<div class="col-sm-3">&nbsp;
</div>

<div class="col-sm-6">
<%= form_for @list do |f|%>
    <div class="form-group">
        <%= f.text_field :name, :placeholder => "Your name", :class => "form-control" %>
    </div>
    <div class="form-group">
        <%= f.country_select :country, :class => "form-control" %>
    </div>
    <div class="form-group">
        <%= f.text_field :town, :placeholder => "Town/City", :class => "form-control" %>
    </div>
    <div class="form-group">
        <%= f.text_field :postcode, :placeholder => "Post Code", :class => "form-control" %>
    </div>
    <div class="form-group">
        <%= f.text_field :phone, :placeholder => "Phonenr", :class => "form-control" %>
    </div>
    <br>
    <%= f.submit "Save List", :class => "btn btn-success btn-large"%>
<% end %>
</div>
<div class="col-sm-3"></div>

app/views/lists/show.html.erb
<h2><%= @list.name %></h2>
<div class="row">

<div class="col-sm-3">
    <div class="card">
  <div class="card-body">
    <h5 class="card-title"></h5>
      <span class=""><strong>Country:</strong></span>
      <p class=""><%= @list.country %></p>
      <span class=""><strong>Town:</strong></span>
      <p class=""><%= @list.town %></p>
      <span class=""><strong>Postcode:</strong></span>
      <p class=""><%= @list.postcode %></p>
      <% if user_signed_in? %>
        <span class=""><strong>Phone:</strong></span>
        <p class=""><%= @list.phone %></p>
        <span class=""><strong>Email:</strong></span>
        <p class=""><%= User.find(@list.user_id).email %></p>
        <% else %>
        <span class=""><strong>Get the contact details by logging in first.</strong></span>
        <p><%= link_to "Log In/Create Account", new_user_session_url %></p>
        <% end %>
    </div>
    </div>
</div>

<div class="col-sm-6">

<ul class="list-group list-group-flush">
<% if @list.listitems.exists? %>
    <% @list.listitems.each do |ll| %>
        <li class="list-group-item d-flex justify-content-between align-items-center"><%= ll.item_text %>
        <span class="badge badge-primary badge-pill"><%= ll.item_count %></span></li>
    <% end %>
<% else %>
        <span>List is currently empty</span>
<% end %>
</ul>
<br>

<% if user_signed_in? && @list.user_id == current_user.id %>
    <%= form_for([@list, @list.listitems.build], {class: "inline-form"}) do |f| %>
        <div class="form-group">
            <%= f.text_field :item_text, :placeholder => "Name item", :class => "form-control" %>
        </div>
        <div class="form-group">
            <%= f.text_field :item_count, :placeholder => "Item count", :class => "form-control" %>
        </div>
        <%= f.submit "Save", :class => "btn btn-success" %>
    <% end %>
    <br>
    <%= link_to 'Destroy', @list, :method => :delete, :confirm => "Are you sure?", :class => "btn btn-danger" %>
    <br>
<% end %>

<% if user_signed_in? %>
    <% if @list.assigned_to == current_user.id? %>
        <br>
    <% else%>
        <br>
        <%= button_to 'Assign To Me', assigntome_path, :class => "btn btn-info" %>
    <% end %>
<% end %>

</div>

<div class="col-sm-6">
</div>

</div>

app/views/partials/_list_item.html.erb
<p><%= listitem.item_text %></p>